ethnodoc_search:
    path:     /search/{page}/{type}/{id}
    defaults: { _controller: EthnoDocPublicationBundle:Search:search, type: null, id: null, page: 0 }

ethnodoc_autocomplete:
    path:       /autocomplete/{searchPhrase}
    defaults: { _controller: EthnoDocPublicationBundle:Search:autocomplete, searchPhrase: null }
