ethnodoc_search:
    path:     /search/{type}/{id}
    defaults: { _controller: EthnoDocPublicationBundle:Search:search, type: null, id: null }

ethnodoc_autocomplete:
  path:       /autocomplete/{searchPhrase}
  defaults: { _controller:EthnoDocPublicationBundle:Search:autocomplete, searchPhrase: null }