ethnodoc_search:
    path:     /search/{page}/{type}/{id}
    defaults: { _controller: EthnoDocPublicationBundle:Search:search, type: null, id: null, page: 1 }

ethnodoc_autocomplete:
    path:       /autocomplete/{searchPhrase}
    defaults: { _controller: EthnoDocPublicationBundle:Search:autocomplete, searchPhrase: null }

projects:
    path:     /projects
    defaults: { _controller: EthnoDocPublicationBundle:Page:projects }

calendar:
    path:     /calendar
    defaults: { _controller: EthnoDocPublicationBundle:Page:calendar }

partners:
    path:     /partners
    defaults: { _controller: EthnoDocPublicationBundle:Page:partners }

network:
    path:     /network
    defaults: { _controller: EthnoDocPublicationBundle:Page:network }

missions:
    path:     /missions
    defaults: { _controller: EthnoDocPublicationBundle:Page:missions }

volunteer:
    path:     /volunteer
    defaults: { _controller: EthnoDocPublicationBundle:Page:volunteer }

register:
    path:     /register
    defaults: { _controller: EthnoDocPublicationBundle:Page:register }
