<?php

namespace EthnoDoc\PublicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * spokenArchiveNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class spokenArchiveNoteRepository extends EntityRepository
{
}
